name: Above the sheets
favicon: null
layout_spectrum: 0.25368
typography_spectrum: 0.25368
title: Above the sheets
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cacbcf'
    - '#484b50'
    - '#6a6f75'
    - '#dc570c'
    - '#fe6f2d'
  brandStrength: 0.9265615697950125
  lightness: 0.032920392230153084
  saturation: 0.6800539409741759
  rhythmicContrast: 0.37746579805389047
purpose: []
